### ISSUE TITLE
Inflect.php

### ISSUE THREAD

**Issue by busayo** [andela-oisola/potato-orm#1]
In `pluralize()`, there is repetition like 

```php
if ( preg_match($pattern, $string) )
                return preg_replace($pattern, $result, $string);
```
Look for a way to create another method for it so that you can just call it.

**Comment by andela-oisola** [comment]
I couldn't find a way to do this. The solution I tried was giving errors.

**Comment by busayo** [comment]
How did you do it and what kinda erros were you getting?

**Comment by andela-oisola** [comment]
I created a function that takes 3 arguments ($pattern, $result, $string), and I dropped this code you snapshot here into the function. And I just called the new function I created with the 3 parameters.

**Comment by busayo** [comment]
So what kinda error was thrown?

**Comment by andela-oisola** [comment]
The pluralize function did not do its job. It's outputing the input passed into it.

**Comment by busayo** [comment]
Wait, was that the exact error it gave?

**Comment by andela-oisola** [comment]
I ran my tests and it shows in the actual/expected result, there I saw that the pluralize() wasn't doing it 's job.
