### ISSUE TITLE
README

### ISSUE THREAD

**Issue by busayo** [andela-oisola/potato-orm#3]
```php
//To update data
$car = new Car();
$car = $car::find(2);
$thing->name = "Veyron";
$thing->save();

//To delete data
$car = Property::destroy(1);
```

Update data...How can you instantiate a class and then use the scope resolution operator `::` to call a static method?...then you used $car to find, all of a sudden it automatically turned to $thing...: :flushed:  How?

In deleting data, what does it return to the $car variable?

**Comment by busayo** [comment]
I can see a `.travis.yml` file but there is no connection to Travis CI. Connect and indicate in the README  with a badge that shows build as `passing` or `failing` as status

**Comment by andela-oisola** [comment]
These two issues have been attended to.
